# Generated by Django 3.0.2 on 2020-01-15 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 14, 51, 53, 924565, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='postpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
