# Generated by Django 3.0.2 on 2020-01-21 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200115_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='intro',
            new_name='subtitle',
        ),
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 16, 10, 3, 533009, tzinfo=utc)),
        ),
    ]
