# Generated by Django 3.0.2 on 2020-01-21 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200121_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 22, 8, 25, 576550, tzinfo=utc)),
        ),
    ]
