# Generated by Django 3.0.2 on 2020-01-22 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200121_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 15, 45, 11, 451547, tzinfo=utc)),
        ),
    ]
