# Generated by Django 3.0.2 on 2020-01-22 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200122_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 15, 47, 48, 189249, tzinfo=utc)),
        ),
    ]
