# Generated by Django 3.0.2 on 2020-01-22 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200122_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 18, 36, 51, 57174, tzinfo=utc)),
        ),
    ]
