# Generated by Django 3.0.2 on 2020-01-22 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 22, 20, 41, 41, 318844, tzinfo=utc)),
        ),
    ]
