# Generated by Django 3.0.2 on 2020-01-23 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200122_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 15, 18, 54, 850305, tzinfo=utc)),
        ),
    ]
