# Generated by Django 3.0.2 on 2020-01-27 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20200123_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 18, 53, 2, 951760, tzinfo=utc)),
        ),
    ]
