# Generated by Django 3.0.2 on 2020-01-27 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20200127_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 19, 34, 58, 973571, tzinfo=utc)),
        ),
    ]
