# Generated by Django 3.0.2 on 2020-01-27 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20200127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 19, 35, 0, 721859, tzinfo=utc)),
        ),
    ]
