# Generated by Django 3.0.2 on 2020-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200127_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='date',
            field=models.DateField(),
        ),
    ]
