# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[(b'wp-base', b'WP Base'), (b'wp-gallery', b'WP Gallery'), (b'wp-home', b'WP Home'), (b'wp-guide', b'WP Guide'), (b'wp-aca-guide', b'ACA Guide'), (b'wp-wcsb-base', b'PSFaM Base'), (b'wp-calendar', b'WP Calendar'), (b'wp-7_5', b'WP 2-Col. 7/5'), (b'wp-5_7', b'WP 2-Col. 5/7'), (b'wp-8_4', b'WP 2-Col. 8/4'), (b'wp-6_6', b'WP 2-Col. 6/6'), (b'wp-9_3', b'WP 2-Col. 9/3'), (b'wp-10_2', b'WP 2-Col. 10/2'), (b'wp-sitemap', b'WP Sitemap'), (b'wp-2_8', b'WP 2-Col. 2/8'), (b'wp-2_7_3', b'WP 3-Col. 2/7/3'), (b'wp-monitor', b'Monitor Display')], default=b'wp-base', max_length=255, verbose_name='template'),
        ),
    ]
