# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simplewiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Article title')),
                ('slug', models.SlugField(blank=True, help_text="Letters, numbers, underscore and hyphen. Do not use reserved words 'create', 'history' and 'edit'.", max_length=100, verbose_name='slug')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False, verbose_name='Locked for editing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=simplewiki.models.get_attachment_filepath, verbose_name='Attachment')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplewiki.Article', verbose_name='Article')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=255, verbose_name='Permission name')),
                ('can_read', models.ManyToManyField(blank=True, help_text='Select none to grant anonymous access.', related_name='read', to=settings.AUTH_USER_MODEL)),
                ('can_write', models.ManyToManyField(blank=True, help_text='Select none to grant anonymous access.', related_name='write', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article permission',
                'verbose_name_plural': 'Article permissions',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of change')),
                ('revision_date', models.DateTimeField(auto_now_add=True, verbose_name='Revision date')),
                ('contents', models.TextField(verbose_name='Contents (Use MarkDown format)')),
                ('contents_parsed', models.TextField(blank=True, editable=False, null=True)),
                ('counter', models.IntegerField(default=1, editable=False, verbose_name='Revision#')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplewiki.Article', verbose_name='Article')),
                ('previous_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='simplewiki.Revision')),
                ('revision_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_revision_user', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'article revision',
                'verbose_name_plural': 'article revisions',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rev', to='simplewiki.Revision'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Affects URL structure and possibly inherits permissions', null=True, on_delete=django.db.models.deletion.CASCADE, to='simplewiki.Article', verbose_name='Parent article slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='permissions',
            field=models.ForeignKey(blank=True, help_text='Permission group', null=True, on_delete=django.db.models.deletion.CASCADE, to='simplewiki.Permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='article',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Sets a symmetrical relation other articles', related_name='_article_related_+', to='simplewiki.Article', verbose_name='Related articles'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
