# Generated by Django 3.0.2 on 2020-01-09 22:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinepage',
            name='gallery',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock())], icon='image'))], null=True),
        ),
    ]
