# Generated by Django 3.0.2 on 2020-01-21 22:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0003_auto_20200109_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlinepage',
            name='gallery',
            field=wagtail.core.fields.StreamField([('image_carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=False))]), icon='image', template='yourapp/blocks/carousel.html'))], blank=True, null=True),
        ),
    ]
