# Generated by Django 3.0.2 on 2020-01-23 16:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_auto_20200122_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinepage',
            name='techniques',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
