# Generated by Django 3.0.2 on 2020-01-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0007_beamlinepage_techniques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beamlinepage',
            old_name='specs',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='beamlinepage',
            old_name='techniques',
            new_name='sidebar',
        ),
    ]
