# Generated by Django 3.0.2 on 2020-01-23 19:44

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0008_auto_20200123_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinepage',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='beamlinepage',
            name='status_color',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Maintenance', 'Maintenance'), ('Down', 'Down'), ('Upgrade', 'Upgrade')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beamlinepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'alignment', 'undo', 'redo']})), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))]),
        ),
    ]
