# Generated by Django 3.0.2 on 2020-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0009_auto_20200123_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlinepage',
            name='status_color',
            field=models.CharField(choices=[('success', 'Normal Operations'), ('warning', 'Maintenance'), ('dark', 'Shutdown'), ('info', 'Upgrade in Progress')], max_length=255),
        ),
    ]
