# Generated by Django 3.0.2 on 2020-01-27 18:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0010_auto_20200123_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinepage',
            name='snippet',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='To be displayed on other parts of the site.'),
        ),
    ]
