# Generated by Django 2.2.9 on 2020-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0013_auto_20200128_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguidepage',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
