# Generated by Django 2.2.9 on 2020-01-29 22:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0014_userguidepage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlinepage',
            name='status_color',
            field=colorfield.fields.ColorField(default='#00FF00', max_length=18),
        ),
    ]
