# Generated by Django 3.0.3 on 2020-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0002_publicationspage_latest_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationspage',
            old_name='categories_api',
            new_name='api',
        ),
        migrations.RemoveField(
            model_name='publicationspage',
            name='latest_api',
        ),
        migrations.RemoveField(
            model_name='publicationspage',
            name='publications_api',
        ),
        migrations.AddField(
            model_name='publicationspage',
            name='acronym',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
