# Generated by Django 3.0.5 on 2020-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0005_auto_20200427_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamlinedisplaypage',
            name='background_url',
            field=models.URLField(blank=True),
        ),
    ]
