# Generated by Django 3.0.5 on 2020-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_beamlinedisplaypage_background_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedpage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Height of target page, in pixels', null=True),
        ),
    ]
