# Generated by Django 3.0.5 on 2020-10-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecolumnpage',
            name='submenu',
            field=models.BooleanField(default=False),
        ),
    ]
