# Generated by Django 3.2 on 2024-10-28 21:41

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


def remove_deleted_revisions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Revision = apps.get_model("wagtailcore.Revision")

    valid_types = set(ContentType.objects.values_list('pk', flat=True))
    Revision.objects.exclude(content__content_type__in=valid_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_onecolumnpage_submenu'),
        ("wagtailcore", "0070_rename_pagerevision_revision"),
    ]

    run_before = [
        ("wagtailcore", "0071_populate_revision_content_type")
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolumnpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='subsitehomepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='subsitepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='twocolumnpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='twocolumnpage',
            name='sidebar',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, use_json_field=True),
        ),
        migrations.RunPython(
            remove_deleted_revisions,
            migrations.RunPython.noop,
        )
    ]
