# Generated by Django 3.0.3 on 2020-02-05 16:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('personnel', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('person', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('hover_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.TextBlock()), ('position', wagtail.blocks.TextBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('phone', wagtail.blocks.TextBlock(required=False)), ('office', wagtail.blocks.TextBlock(required=False))]), icon='user'))], blank=True, null=True)),
                ('sidebar', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
