# Generated by Django 3.2 on 2024-10-28 21:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='personnel',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('person', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('hover_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.TextBlock()), ('position', wagtail.blocks.TextBlock(required=False)), ('email', wagtail.blocks.EmailBlock(required=False)), ('phone', wagtail.blocks.TextBlock(required=False)), ('office', wagtail.blocks.TextBlock(required=False))]), icon='user'))], blank=True, null=True, use_json_field=True),
        ),
    ]
