# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:01


from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beamline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OnCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'get_latest_by': 'date',
                'verbose_name': 'Local Contact',
                'verbose_name_plural': 'Local Contacts',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('proposal_id', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('account', models.CharField(blank=True, help_text=b"Principle Investigator's Account Name", max_length=300, null=True, verbose_name=b'PI Account')),
            ],
            options={
                'ordering': ['last_name'],
                'verbose_name': 'Active Proposal',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[(b'Maintenance', b'Maintenance Mode'), (b'Shutdown', b'Shutdown Mode'), (b'Development', b'Development Mode'), (b'NormalMode', b'Normal Mode'), (b'Special', b'Special Request/Commissioning'), (b'FacilityRepair', b'Unplanned Facility Repairs')], max_length=60)),
                ('start_date', models.DateField(blank=True)),
                ('first_shift', models.IntegerField(blank=True, choices=[(0, '08:00 - 16:00'), (1, '16:00 - 24:00'), (2, '24:00 - 08:00')])),
                ('end_date', models.DateField(blank=True)),
                ('last_shift', models.IntegerField(choices=[(0, '08:00 - 16:00'), (1, '16:00 - 24:00'), (2, '24:00 - 08:00')])),
            ],
            options={
                'get_latest_by': 'date',
                'verbose_name': 'Facility Status',
                'verbose_name_plural': 'Facility Statuses',
            },
        ),
        migrations.CreateModel(
            name='SupportPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text=b'Ten digit number', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=scheduler.models.get_storage_path, verbose_name='image')),
                ('office', models.CharField(blank=True, max_length=50)),
                ('category', models.IntegerField(choices=[(0, 'Beamline Staff'), (1, 'Students and Postdocs'), (2, 'CLS Technical Support'), (3, 'User Support')])),
            ],
            options={
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=60)),
                ('start_date', models.DateField()),
                ('first_shift', models.IntegerField(choices=[(0, '08:00 - 16:00'), (1, '16:00 - 24:00'), (2, '24:00 - 08:00')])),
                ('end_date', models.DateField()),
                ('last_shift', models.IntegerField(choices=[(0, '08:00 - 16:00'), (1, '16:00 - 24:00'), (2, '24:00 - 08:00')])),
                ('remote', models.BooleanField(default=False)),
                ('mail_in', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'date modified')),
                ('notify', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Beamline')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Proposal')),
            ],
            options={
                'get_latest_by': 'date',
                'verbose_name': 'Beamline Visit',
            },
        ),
        migrations.AlterUniqueTogether(
            name='supportperson',
            unique_together=set([('first_name', 'last_name', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('mode', 'start_date', 'first_shift'), ('mode', 'end_date', 'last_shift')]),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set([('proposal_id',)]),
        ),
        migrations.AddField(
            model_name='oncall',
            name='local_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.SupportPerson'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set([('beamline', 'start_date', 'first_shift'), ('beamline', 'end_date', 'last_shift')]),
        ),
        migrations.AlterUniqueTogether(
            name='oncall',
            unique_together=set([('local_contact', 'date')]),
        ),
    ]
