# Generated by Django 2.2.9 on 2020-01-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportperson',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='account',
            field=models.CharField(blank=True, help_text="Principle Investigator's Account Name", max_length=300, null=True, verbose_name='PI Account'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mode',
            field=models.CharField(choices=[('Maintenance', 'Maintenance Mode'), ('Shutdown', 'Shutdown Mode'), ('Development', 'Development Mode'), ('NormalMode', 'Normal Mode'), ('Special', 'Special Request/Commissioning'), ('FacilityRepair', 'Unplanned Facility Repairs')], max_length=60),
        ),
        migrations.AlterField(
            model_name='supportperson',
            name='category',
            field=models.IntegerField(choices=[(0, 'Beamline Staff'), (1, 'Students and Postdocs'), (2, 'CLS Technical Support'), (3, 'User Support'), (4, 'Past Members')]),
        ),
        migrations.AlterField(
            model_name='supportperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supportperson',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Ten digit number', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.Proposal'),
        ),
    ]
