# Generated by Django 3.0.2 on 2020-01-21 21:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200121_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footer',
            new_name='footer1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
