# Generated by Django 3.0.2 on 2020-01-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_auto_20200121_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name_long',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name_short',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='org_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='org_url',
            field=models.URLField(blank=True, verbose_name='Organization link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
