# Generated by Django 3.0.2 on 2020-01-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200122_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
