# Generated by Django 3.0.2 on 2020-01-22 17:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200122_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='links',
            new_name='column1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='column2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
