# Generated by Django 3.0.2 on 2020-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200122_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call',
            field=models.TextField(blank=True),
        ),
    ]
