# Generated by Django 3.0.2 on 2020-01-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
