# Generated by Django 2.2.9 on 2020-01-29 20:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0015_subsitepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsitepage',
            name='footer1',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='footer2',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='name_long',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='name_short',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='org_img',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='org_url',
        ),
        migrations.RemoveField(
            model_name='subsitepage',
            name='organization',
        ),
        migrations.CreateModel(
            name='SubsiteHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True)),
                ('name_short', models.CharField(blank=True, max_length=40)),
                ('name_long', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('org_url', models.URLField(blank=True, verbose_name='Organization link')),
                ('footer1', wagtail.core.fields.RichTextField(blank=True)),
                ('footer2', wagtail.core.fields.RichTextField(blank=True)),
                ('org_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
