# Generated by Django 2.2.9 on 2020-01-29 21:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200129_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsitehomepage',
            name='footer_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='subsitehomepage',
            name='header_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
