# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100, verbose_name='Address')),
                ('addr2', models.CharField(max_length=100, verbose_name=' ')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, verbose_name='Province/State')),
                ('code', models.CharField(max_length=100, verbose_name='Area Code/ZipCode')),
                ('country', models.CharField(max_length=100)),
                ('sup_name', models.CharField(max_length=100, verbose_name='supervisor Name')),
                ('sup_email', models.EmailField(max_length=254, verbose_name='supervisor Email')),
                ('sup_phone', models.CharField(max_length=100, verbose_name='supervisor Phone')),
                ('undergrad', models.BooleanField()),
                ('masters', models.BooleanField()),
                ('phd', models.BooleanField()),
                ('postdoc', models.BooleanField()),
                ('faculty', models.BooleanField()),
                ('staff', models.BooleanField()),
                ('other', models.BooleanField()),
                ('other_text', models.CharField(max_length=100, verbose_name='Other')),
                ('travel', models.BooleanField(default=False, verbose_name='Requests Travel Assistance')),
                ('visa', models.BooleanField(verbose_name='Requires VISA')),
                ('stay', models.BooleanField(verbose_name='Requests Accommodations')),
                ('crystals', models.BooleanField(verbose_name='bringing crystals')),
                ('research', models.TextField(verbose_name='research Interests')),
                ('benefit', models.TextField(verbose_name='benefit/Experience')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(blank=True, choices=[(0, 'Prof.'), (1, 'Dr.'), (2, 'Mr.'), (3, 'Ms.'), (4, 'Mrs.')], null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100, verbose_name='Address')),
                ('addr2', models.CharField(blank=True, max_length=100, verbose_name=' ')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, verbose_name='Province/State')),
                ('code', models.CharField(max_length=100, verbose_name='Area Code/ZipCode')),
                ('country', models.CharField(max_length=100)),
                ('undergrad', models.BooleanField()),
                ('masters', models.BooleanField()),
                ('phd', models.BooleanField()),
                ('postdoc', models.BooleanField()),
                ('faculty', models.BooleanField()),
                ('staff', models.BooleanField()),
                ('other', models.BooleanField()),
                ('other_text', models.CharField(blank=True, max_length=100, verbose_name='Other')),
                ('sup_name', models.CharField(blank=True, max_length=100, verbose_name='supervisor Name')),
                ('sup_email', models.EmailField(blank=True, max_length=254, verbose_name='supervisor Email')),
                ('sup_phone', models.CharField(blank=True, max_length=100, verbose_name='supervisor Phone')),
                ('talk', models.BooleanField()),
                ('poster', models.BooleanField()),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Poster'), (1, 'Oral')], null=True)),
                ('headline', models.CharField(blank=True, max_length=500, verbose_name='Presentation Title')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='Authors')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('affiliations', models.CharField(blank=True, max_length=500, verbose_name='Author Affiliations')),
                ('diet', models.TextField(blank=True, verbose_name='Dietary Concerns')),
                ('mixer', models.BooleanField(verbose_name='Attending Mixer')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('email',)]),
        ),
    ]
