# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 15:01
from __future__ import unicode_literals

import blog.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'verbose_name': 'blog roll',
                'verbose_name_plural': 'blog roll',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'ordering': ('title',),
                'db_table': 'blog_categories',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique_for_date=b'publish', verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to=blog.models.get_storage_path, verbose_name='image')),
                ('link', models.CharField(blank=True, help_text=b'Link to original publication', max_length=300, verbose_name='link')),
                ('citation', models.CharField(blank=True, max_length=300, verbose_name='citation')),
                ('body', models.TextField(verbose_name='body')),
                ('tease', models.TextField(blank=True, help_text='This appears on the homepage content slider if the post is highlighted.', verbose_name='tease')),
                ('highlight', models.BooleanField(default=False, help_text='Should this item be featured in the content slider on the home page?', verbose_name='highlight')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Public')], default=2, verbose_name='status')),
                ('publish', models.DateTimeField(default=datetime.datetime.now, verbose_name='publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('tags', models.TextField()),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category')),
            ],
            options={
                'get_latest_by': 'publish',
                'ordering': ('-publish',),
                'verbose_name_plural': 'News Items',
                'db_table': 'blog_posts',
                'verbose_name': 'News Item',
            },
        ),
    ]
